CREATE TABLE `cliente` (
`id` INT(11) NOT NULL AUTO_INCREMENT,
`nome` VARCHAR(15) NOT NULL,
`cpf` BIGINT(11) NOT NULL,
`email` VARCHAR(100) NOT NULL,
`data_cadastro` DATE NOT NULL,
PRIMARY KEY (`id`))